[build-system]

requires = ["setuptools",
            "setuptools_scm",
            "wheel",
            "extension-helpers",
            "cython"
            ]

build-backend = 'setuptools.build_meta'
